### ISSUE TITLE
RealTime model problem -- name 'corr_sampler' is not defined

### ISSUE THREAD

**Issue by lee-vius** [princeton-vl/RAFT-Stereo#11]
I tried to run the real time model with the given command on Colab.
But it gives me the following error: (By the way, the full model works well)

Traceback (most recent call last):
  File "demo.py", line 75, in <module>
    demo(args)
  File "demo.py", line 46, in demo
    _, flow_up = model(image1, image2, iters=args.valid_iters, test_mode=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "core/raft_stereo.py", line 110, in forward
    corr = corr_fn(coords1) # index correlation volume
  File "/content/drive/My Drive/Projects/raft-stereo/RAFT-Stereo/core/corr.py", line 49, in __call__
    corr = CorrSampler.apply(self.corr_pyramid[i].squeeze(3), coords/2**i, self.radius)
  File "/content/drive/My Drive/Projects/raft-stereo/RAFT-Stereo/core/corr.py", line 22, in forward
    corr, = corr_sampler.forward(volume, coords, radius)
NameError: name 'corr_sampler' is not defined

Any idea why it happens?

**Comment by lahavlipson** [comment]
This happens because of the `--corr_implementation reg_cuda` flag. Either changing it to `--corr_implementation reg` or compiling the faster correlation sampler (see [(Optional) Faster Implementation](https://github.com/princeton-vl/RAFT-Stereo#optional-faster-implementation)) should resolve the issue.

I updated the readme to clarify: f1fa15abd34187d101806f65b813f4d9d6f93ab0

**Comment by lahavlipson** [comment]
Closing this issue.
