### ISSUE TITLE
Parameter missing "args.context_norm"

### ISSUE THREAD

**Issue by tb2-sy** [princeton-vl/RAFT-Stereo#94]
Thanks for your nice work, when I use "real_time_model" for inference, class RAFTStereo requires norm_fn=args.context_norm, but the error args seems to not exist in this parameter.

**Comment by ideallyworld** [comment]
hi,
  Do you have fixed this problem now? I meet the same problem with you.
THX

Traceback (most recent call last):
  File "test_prototype.py", line 140, in <module>
    disparity = disparity_from_stereo_raft2d(img_rect*255., img_rect_2*255., 'real_time_model', device)
  File "F:\Test\Test-neualpassthrough\NeuralPassthrough\code\stereo_depth.py", line 61, in disparity_from_stereo_raft2d
    model = torch.nn.DataParallel(RAFTStereo(args), device_ids=[0])
  File "F:\Test\Test-neualpassthrough\NeuralPassthrough\code\third_party\RAFT_Stereo\core\raft_stereo.py", line 29, in __init__
    self.cnet = MultiBasicEncoder(output_dim=[args.hidden_dims, context_dims], norm_fn=args.context_norm, downsample=args.n_downsample)
AttributeError: 'Namespace' object has no attribute 'context_norm'
